chore: lambda update 확인 로직 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,20 +49,22 @@ jobs:
             --s3-bucket ${{ secrets.S3_BUCKET_NAME }} \
             --s3-key mood-writer-0.0.1-SNAPSHOT.zip
 
-      - name: Check Lambda Update Status
-        env:
-          AWS_LAMBDA_FUNCTION_NAME: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
-        run: |
+          # ✅ Lambda 업데이트가 완료될 때까지 계속 상태 확인
+          echo "Checking Lambda update status..."
           while true; do
-            STATUS=$(aws lambda get-function-configuration --function-name "$AWS_LAMBDA_FUNCTION_NAME" --query "State" --output text)
-            if [ "$STATUS" == "Active" ]; then
-              echo "✅ Lambda function is ready for configuration update."
+            STATUS=$(aws lambda get-function-configuration --function-name "$AWS_LAMBDA_FUNCTION_NAME" --query "LastUpdateStatus" --output text)
+            if [ "$STATUS" == "Successful" ]; then
+              echo "✅ Lambda function code update completed successfully."
               break
+            elif [ "$STATUS" == "Failed" ]; then
+              echo "❌ Lambda function code update failed."
+              exit 1
             else
               echo "⏳ Lambda function is still updating. Waiting for 5 seconds..."
               sleep 5
             fi
           done
+      
 
       - name: Update Lambda Environment Variables
         env:
